---
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ debian_target_hostname }}"
    use: debian

- name: Add SSH public key to vagrant user
  when:
    - debian_is_vagrant
  block:
    - name: Ensure /home/vagrant/.ssh directory is present
      ansible.builtin.file:
        path: /home/vagrant/.ssh
        owner: vagrant
        group: vagrant
        mode: '0750'
        state: directory

    - name: Ensure authorized_keys file is present
      ansible.builtin.copy:
        src: authorized_keys
        dest: /home/vagrant/.ssh/authorized_keys
        owner: vagrant
        group: vagrant
        mode: '0600'

- name: Add SSH trusted CA certificate
  when:
    - debian_add_ssh_trusted_ca_cert
  block:
    - name: Copy SSH trusted CA certificate
      become: true
      ansible.builtin.copy:
        src: "{{ debian_ssh_trusted_ca_cert_path }}"
        dest: /etc/ssh/trusted-user-ca-key.pem
        owner: root
        group: root
        mode: '0600'

    - name: Add SSH trusted CA certificate to sshd_config
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?TrustedUserCAKeys'
        line: "TrustedUserCAKeys /etc/ssh/trusted-user-ca-key.pem"
        state: present

- name: Add SSL CA certificates
  when:
    - debian_ssl_ca_certificates | length > 0
  loop: "{{ debian_ssl_ca_certificates }}"
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/share/ca-certificates/
    owner: root
    group: root
    mode: '0644'
  notify:
    - _debian_update_ca_trust

- name: Install cloud-init
  when:
    - debian_install_cloud_init
  block:
    - name: Install cloud-init
      become: true
      ansible.builtin.apt:
        name:
          - cloud-init
        state: present

    - name: Configure cloud-init
      become: true
      ansible.builtin.copy:
        content: "manual_cache_clean: True "
        dest: /etc/cloud/cloud.cfg.d/99-manual.cfg
        owner: root
        group: root
        mode: '0644'

- name: Perform autoremove
  become: true
  ansible.builtin.apt:
    autoremove: true

- name: Clean repository caches
  become: true
  ansible.builtin.apt:
    autoclean: true

- name: Truncate any logs
  become: true
  ansible.builtin.shell: find /var/log -type f -exec truncate --size=0 {} \;
  changed_when: true

- name: Enumerate contents of /tmp and /var/tmp
  become: true
  ansible.builtin.find:
    paths:
      - /tmp
      - /var/tmp
    file_type: any
    hidden: true
    recurse: true
  register: _tmp_contents

- name: Remove all files
  loop: "{{ _tmp_contents.files }}"
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  ignore_errors: true
  loop_control:
    label: "{{ item.path }}"
  tags:
    - always
    - skip_ansible_lint

- name: Remove unnecessary files before shutdown
  loop:
    - /etc/ssh/ssh_host_rsa_key
    - /etc/ssh/ssh_host_rsa_key.pub
    - /etc/ssh/ssh_host_dsa_key
    - /etc/ssh/ssh_host_dsa_key.pub
    - /etc/ssh/ssh_host_ecdsa_key
    - /etc/ssh/ssh_host_ecdsa_key.pub
    - /etc/ssh/ssh_host_ed25519_key
    - /etc/ssh/ssh_host_ed25519_key.pub
    - /var/lib/systemd/random-seed
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  notify:
    - _debian_regenerate_ssh_host_keys

- name: Remove netplan machine ID
  become: true
  ansible.builtin.command: truncate -s 0 /etc/machine-id
  changed_when: true

- name: Remove unnecessary files before shutdown
  become: true
  ansible.builtin.file:
    path: /root/.wget-hsts
    state: absent

- name: Set history size to 0
  become: true
  ansible.builtin.shell: export HISTSIZE=0
  changed_when: true
  tags:
    - always
    - skip_ansible_lint
